### ISSUE TITLE
Log In a User (Feature 0)

### ISSUE THREAD

**Issue by Adrian-gh1** [Adrian-gh1/Mod-4-Project#4]
Logs in a current user with valid credentials and returns the current user's information.

- [x] Successful response includes the user's `id`, `firstName`, `lastName`, and `email`
- [x] Error response with status 401 is given when invalid credentials are given
- [x] Error response with status 400 is given when body validations for the `email`, `firstName`, or `lastName` are violated

**Comment by Adrian-gh1** [comment]
- [ ] Reviewed by Adrian
- [ ] Reviewed by Tina
- [ ] Pushed to main
- [ ] Reviewed on website by Adrian
- [ ] Reviewed on website by Tina

**Comment by TingyangZhou** [comment]
- [x] changed "Bad request." to "Bad Request"
