### ISSUE TITLE
Get all Spots

### ISSUE THREAD

**Issue by Adrian-gh1** [Adrian-gh1/Mod-4-Project#6]
Returns all the spots.

- [x] Seed data exists in the database for spots to be returned.
- [x] Successful response includes each spot in the database.
- [x] Spot data returned includes the `id`, `ownerId`, `address`, `city`, `state`, `country`, `lat`, `lng`, `name`, `description`, `price`, `createdAt`, `updatedAt`, `previewImage`, and `avgRating`

**Comment by TingyangZhou** [comment]
- [x] create spot, spotImage, and review models

**Comment by TingyangZhou** [comment]
- [x] change 'spot:' to 'Spot:' in res.Json()
